"""add_legal_name_to_registrations

Revision ID: 595c6a7763db
Revises: 44b25039ea94
Create Date: 2026-09-14 05:07:53.733473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595c6a7763db'
down_revision: Union[str, Sequence[str], None] = '44b25039ea94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gst_registrations', sa.Column('legal_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gst_registrations', 'legal_name')
    # ### end Alembic commands ###
