import { useMemo, useState, type DragEvent } from "react";
import {
  AlertTriangle, Archive, ArrowRight, Check, ChevronDown, ChevronRight, CircleDot,
  Download, FileCheck2, FileClock, FileSpreadsheet, Filter, History, Inbox, Layers3,
  Plus, RotateCcw, Save, Search, Stamp, Upload, X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { cn } from "@/lib/utils";
import {
  attentionItems, auditEvents, categoryRows, clients, delayedItems, initialItcDecisions,
  mappings, priorDrafts, receiptTotals, reconRows, reviewNotes, runHistory, salesRows,
  salesSummary, sourceRows, taxHeads, worksheetRows, adjustmentTypes,
  type Client, type ItcDecision, type ReconRow,
} from "@/mock/data";
import { EmptyState, Eyebrow, Money, PaperSection, StatusChip } from "./primitives";

type Navigate = (view: string) => void;

export function BoardScreen({ navigate }: { navigate: Navigate }) {
  const [updated, setUpdated] = useState(false);
  return <div className="space-y-6 animate-fade-in">
    <div className="flex flex-wrap items-end justify-between gap-4">
      <div><Eyebrow className="text-primary">August departures</Eyebrow><h2 className="mt-1 font-display text-4xl font-semibold md:text-6xl">Everything due, at a glance.</h2></div>
      <Button variant="outline" onClick={() => setUpdated((value) => !value)}><RotateCcw /> Simulate update</Button>
    </div>
    <section>
      <div className="mb-3 flex items-center gap-2"><CircleDot className="size-4 text-status-needs"/><Eyebrow>Boarding now — needs you</Eyebrow></div>
      <div className="grid gap-3 lg:grid-cols-3">
        {attentionItems.map((item) => <article className="ticket-card" key={item.client}>
          <div><Eyebrow className="text-primary">{item.count}</Eyebrow><h3 className="mt-1 font-display text-2xl">{item.client}</h3><p className="mt-2 text-sm text-muted-foreground">{item.need}</p></div>
          <Button size="sm" onClick={() => navigate(item.client === "Client B" ? "worksheet" : "reconciliation")}>Open <ArrowRight /></Button>
        </article>)}
      </div>
    </section>
    <div className="delayed-strip"><AlertTriangle/><Eyebrow>Delayed</Eyebrow><span>{delayedItems[0]}</span><Button size="sm" variant="outline" onClick={() => navigate("workspace")}>Open</Button></div>
    <section className="departure-board">
      <div className="flex items-center justify-between border-b border-board-line px-4 py-3"><div><Eyebrow className="text-board-muted">GST Helper desk</Eyebrow><h3 className="font-display text-2xl text-board-ink">Departures</h3></div><span className="font-figures text-xs text-board-muted">29 AUG · 20:56</span></div>
      <div className="board-scroll"><div className="min-w-[980px]">
        <div className="board-grid board-head"><span>Client</span><span>Period</span><span>Sales</span><span>Purchases & ITC</span><span>Tax worksheet</span><span>Remarks</span></div>
        {clients.map((client, index) => <button className="board-grid board-row" onClick={() => navigate("workspace")} key={client.id}>
          <span className="board-client"><b>{client.name}</b><small>{client.type}</small></span><FlipTile delay={index * 45}>AUG 2026</FlipTile><FlipTile delay={index * 45 + 25}>{client.sales}</FlipTile><FlipTile delay={index * 45 + 50}>{client.purchases}</FlipTile><FlipTile delay={index * 45 + 75}>{updated && client.id === "client-a" ? "READY FOR APPROVAL" : client.worksheet}</FlipTile><FlipTile delay={index * 45 + 100} tone={client.tone}>{updated && client.id === "client-a" ? "CHECK DRAFT" : client.remarks}</FlipTile>
        </button>)}
      </div></div>
    </section>
  </div>;
}

function FlipTile({ children, tone = "waiting", delay = 0 }: { children: string; tone?: Client["tone"]; delay?: number }) {
  return <span className={cn("flip-tile", `flip-${tone}`)} style={{ animationDelay: `${delay}ms` }}>{children}</span>;
}

export function ClientsScreen({ navigate }: { navigate: Navigate }) {
  const [query, setQuery] = useState("");
  const filtered = clients.filter((client) => `${client.name} ${client.type} ${client.reference}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="space-y-6 animate-fade-in"><div className="max-w-md"><label className="sr-only" htmlFor="client-search">Search clients</label><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input id="client-search" className="pl-9" placeholder="Search client, type or reference…" value={query} onChange={(e) => setQuery(e.target.value)}/></div></div>
    {filtered.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((client) => <article className="folder-card" key={client.id}><div className="folder-tab">{client.reference}</div><div className="folder-body"><div><Eyebrow>{client.type}</Eyebrow><h2 className="mt-1 font-display text-3xl">{client.name}</h2></div><div className="my-5 grid grid-cols-3 gap-2"><MiniTile label="Sales" value={client.sales}/><MiniTile label="Purchase" value={client.purchases}/><MiniTile label="Worksheet" value={client.worksheet}/></div><div className="flex items-center justify-between"><StatusChip tone={client.tone}>{client.remarks}</StatusChip><Button size="sm" onClick={() => navigate("workspace")}>Open workspace <ArrowRight/></Button></div></div></article>)}</div> : <EmptyState title="No folders found" detail="Try a client name, business type or demo reference."/>}
  </div>;
}

function MiniTile({ label, value }: { label: string; value: string }) { return <div className="mini-tile"><Eyebrow>{label}</Eyebrow><span>{value}</span></div>; }

export function WorkspaceScreen({ navigate }: { navigate: Navigate }) {
  const [open, setOpen] = useState("purchase"); const [ack, setAck] = useState(false); const [note, setNote] = useState(""); const [committed, setCommitted] = useState(false); const [ran, setRan] = useState(false);
  return <div className="space-y-6 animate-fade-in"><div className="grid gap-5 xl:grid-cols-2"><UploadTray title="Purchase register" version="V3 · Preview" icon={<FileSpreadsheet/>} open={open === "purchase"} setOpen={() => setOpen(open === "purchase" ? "" : "purchase")}/><UploadTray title="Statement · GSTR-2B demo format" version="V2 · Committed" icon={<FileCheck2/>} open={open === "statement"} setOpen={() => setOpen(open === "statement" ? "" : "statement")}/></div>
    {open && <PaperSection className="overflow-hidden"><div className="section-heading"><div><Eyebrow>Source rows · preview</Eyebrow><h2 className="font-display text-2xl">20 rows · 3 invalid</h2></div><StatusChip tone="needs">Needs acknowledgement</StatusChip></div><div className="table-wrap"><table><thead><tr><th>Record</th><th>Date</th><th>Supplier</th><th>Taxable</th><th>Tax</th><th>Validation</th></tr></thead><tbody>{sourceRows.map((row) => <tr key={row.id}><td className="id-cell">{row.id}</td><td className="id-cell">{row.date}</td><td>{row.supplier}</td><td><Money value={row.taxable}/></td><td><Money value={row.tax}/></td><td>{row.state === "Invalid" ? <span className="validation-note">{row.note}</span> : <StatusChip tone="done">Valid</StatusChip>}</td></tr>)}</tbody></table></div><div className="commit-bar"><label className="flex items-start gap-3 text-sm"><Checkbox checked={ack} onCheckedChange={(v) => setAck(v === true)}/><span>I reviewed the invalid rows and accept that they will be excluded.</span></label><Input value={note} onChange={(e) => setNote(e.target.value)} placeholder="Required note for this import…"/><Button disabled={!ack || !note.trim()} title={!ack || !note.trim() ? "Acknowledge invalid rows and add a note first" : undefined} onClick={() => setCommitted(true)}>{committed ? <Check/> : <Archive/>}{committed ? "Committed" : "Commit import"}</Button></div></PaperSection>}
    <PaperSection><div className="section-heading"><div><Eyebrow>Reconciliation inputs</Eyebrow><h2 className="font-display text-2xl">Choose committed versions</h2></div><Button disabled={!committed} title={!committed ? "Commit the purchase preview first" : undefined} onClick={() => setRan(true)}>Run reconciliation <ArrowRight/></Button></div><div className="grid gap-3 sm:grid-cols-2"><VersionChoice title="Purchase register" version={committed ? "V3 · Committed" : "No committed version"}/><VersionChoice title="Statement" version="V2 · Committed"/></div>{ran && <div className="mt-4 flex items-center justify-between border-t border-ledger-line pt-4"><StatusChip tone="done">Run complete · RUN-2508-04</StatusChip><Button variant="outline" size="sm" onClick={() => navigate("reconciliation")}>Review results</Button></div>}</PaperSection>
    <section><div className="mb-3 flex items-center gap-2"><History className="size-4"/><Eyebrow>Run ledger</Eyebrow></div><div className="ledger-list">{runHistory.map((run) => <div className="ledger-entry" key={run.id}><span className="id-cell">{run.id}</span><span>{run.time}</span><span>{run.detail}</span><StatusChip tone={run.state === "Current" ? "done" : "waiting"}>{run.state}</StatusChip></div>)}</div></section>
  </div>;
}

function UploadTray({ title, version, icon, open, setOpen }: { title: string; version: string; icon: React.ReactNode; open: boolean; setOpen: () => void }) {
  const [file, setFile] = useState(""); const drop = (event: DragEvent) => { event.preventDefault(); setFile(event.dataTransfer.files[0]?.name ?? "demo-register.xlsx"); };
  return <PaperSection className={cn("in-tray", open && "ring-2 ring-primary")}><div className="flex justify-between gap-4"><span className="tray-icon">{icon}</span><StatusChip tone={version.includes("Committed") ? "done" : "needs"}>{version}</StatusChip></div><h2 className="mt-5 font-display text-2xl">{title}</h2><label className="drop-zone" onDragOver={(e) => e.preventDefault()} onDrop={drop}><Upload/><span>{file || "Drop a file here or choose one"}</span><input className="sr-only" type="file" onChange={(e) => setFile(e.target.files?.[0]?.name ?? "")}/></label><div className="mt-4 flex justify-between"><select className="native-select" aria-label={`${title} version`}><option>{version}</option><option>V1 · Superseded</option></select><Button variant="outline" size="sm" onClick={setOpen}>{open ? "Hide rows" : "Expand rows"}<ChevronDown className={cn(open && "rotate-180")}/></Button></div></PaperSection>;
}
function VersionChoice({ title, version }: { title: string; version: string }) { return <label className="version-choice"><input type="radio" defaultChecked name={title}/><span><Eyebrow>{title}</Eyebrow><b className="font-figures text-sm">{version}</b></span></label>; }

export function ReconciliationScreen() {
  const [finding, setFinding] = useState("all"); const [review, setReview] = useState("all"); const [selected, setSelected] = useState<ReconRow | null>(null);
  const filtered = reconRows.filter((row) => (finding === "all" || row.finding === finding) && (review === "all" || row.state === review));
  return <div className="space-y-6 animate-fade-in"><div className="grid gap-3 sm:grid-cols-3"><BigNumber value="7" label="Exact matches"/><BigNumber value="25" label="Result groups"/><BigNumber value="40" label="Source rows"/></div><PaperSection><div className="section-heading"><div><Eyebrow>Result ledger</Eyebrow><h2 className="font-display text-2xl">Reconciliation findings</h2></div><div className="flex flex-wrap gap-2"><FilterSelect value={finding} setValue={setFinding} label="Finding" options={["all","matched","amount_mismatch","date_conflict","duplicate_candidate","books_only","statement_only","validation_error"]}/><FilterSelect value={review} setValue={setReview} label="Review state" options={["all","unresolved","investigating","explained","correction_required"]}/></div></div><div className="table-wrap"><table><thead><tr><th>Result</th><th>Purchase</th><th>Statement</th><th>Finding</th><th>Review state</th><th>Taxable</th><th>Difference</th></tr></thead><tbody>{filtered.map((row) => <tr className="clickable-row" key={row.id} onClick={() => setSelected(row)}><td className="id-cell">{row.id}</td><td className="id-cell">{row.purchase}</td><td className="id-cell">{row.statement}</td><td><StatusChip tone={row.finding === "matched" ? "done" : row.finding === "validation_error" ? "blocked" : "needs"}>{row.finding.replaceAll("_", " ")}</StatusChip></td><td>{row.state.replaceAll("_", " ")}</td><td><Money value={row.taxable}/></td><td><Money className={row.difference ? "text-destructive" : ""} value={row.difference}/></td></tr>)}</tbody></table></div></PaperSection><EvidenceDrawer row={selected} close={() => setSelected(null)}/></div>;
}

function BigNumber({ value, label }: { value: string; label: string }) { return <PaperSection className="big-number"><strong>{value}</strong><Eyebrow>{label}</Eyebrow></PaperSection>; }
function FilterSelect({ value, setValue, label, options }: { value: string; setValue: (v: string) => void; label: string; options: string[] }) { return <label className="filter-select"><span className="sr-only">{label}</span><Filter/><select value={value} onChange={(e) => setValue(e.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }

function EvidenceDrawer({ row, close }: { row: ReconRow | null; close: () => void }) {
  const [note, setNote] = useState(""); const [state, setState] = useState("investigating");
  return <Sheet open={Boolean(row)} onOpenChange={(open) => !open && close()}><SheetContent className="evidence-sheet sm:max-w-3xl"><SheetHeader><Eyebrow>Evidence folio · {row?.id}</Eyebrow><SheetTitle className="font-display text-3xl">Facing source pages</SheetTitle><SheetDescription>Compare the records, then leave an explicit resolution.</SheetDescription></SheetHeader>{row && <div className="mt-6 space-y-6"><div className="grid gap-3 sm:grid-cols-2"><EvidencePage title="Purchase register" id={row.purchase} value={row.taxable}/><EvidencePage title="Statement" id={row.statement} value={row.taxable - row.difference}/></div>{row.difference !== 0 && <p className="red-ink">taxable_value {row.difference.toFixed(2)} · purchase minus statement</p>}<div><Eyebrow>Review margin</Eyebrow>{reviewNotes.map((entry) => <blockquote className="margin-note" key={entry.time}>{entry.note}<cite>{entry.author} · {entry.time}</cite></blockquote>)}</div><div className="resolution-form"><select className="native-select" value={state} onChange={(e) => setState(e.target.value)}><option>investigating</option><option>explained</option><option>correction_required</option></select><Textarea placeholder="Required resolution note…" value={note} onChange={(e) => setNote(e.target.value)}/><Button disabled={!note.trim()} title={!note.trim() ? "Add a resolution note first" : undefined} onClick={close}>Save resolution</Button></div></div>}</SheetContent></Sheet>;
}
function EvidencePage({ title, id, value }: { title: string; id: string; value: number }) { return <div className="ledger-page"><Eyebrow>{title}</Eyebrow><span className="id-cell mt-5 block">{id}</span><div className="mt-8 flex justify-between"><span>Taxable value</span><Money value={value}/></div><div className="mt-3 flex justify-between"><span>Tax rate</span><span className="id-cell">18.00%</span></div></div>; }

export function SalesScreen() {
  const [filter, setFilter] = useState("All"); const [selected, setSelected] = useState<(typeof salesRows)[number] | null>(null);
  const [states, setStates] = useState<Record<string,string>>({}); const rows = salesRows.filter((row) => filter === "All" || (states[row.id] ?? row.status) === filter);
  return <div className="space-y-6 animate-fade-in"><PaperSection className="sales-upload"><div><Eyebrow>Sales source · V2</Eyebrow><h2 className="font-display text-2xl">August sales register</h2><p className="text-sm text-muted-foreground">19 rows parsed from demo-sales-aug.xlsx</p></div><Button variant="outline"><Upload/> Replace file</Button></PaperSection><div className="summary-strip">{salesSummary.map((item) => <div key={item.label}><strong>{item.value}</strong><Eyebrow>{item.label}</Eyebrow></div>)}</div><div className="grid gap-5 xl:grid-cols-[1fr_270px]"><PaperSection><div className="section-heading"><h2 className="font-display text-2xl">Included rows</h2><FilterSelect value={filter} setValue={setFilter} label="Sales status" options={["All","Reviewed","Excluded","Unresolved","Duplicate","Invalid"]}/></div><div className="table-wrap"><table><thead><tr><th>Record</th><th>Date</th><th>Customer</th><th>Type</th><th>Taxable</th><th>Tax</th><th>Status</th></tr></thead><tbody>{rows.map((row) => <tr className="clickable-row" onClick={() => setSelected(row)} key={row.id}><td className="id-cell">{row.id}</td><td className="id-cell">{row.date}</td><td>{row.customer}</td><td>{row.kind}</td><td><Money value={row.taxable}/></td><td><Money value={row.tax}/></td><td><StatusChip tone={(states[row.id] ?? row.status) === "Reviewed" ? "done" : (states[row.id] ?? row.status) === "Invalid" ? "blocked" : "needs"}>{states[row.id] ?? row.status}</StatusChip></td></tr>)}</tbody></table></div></PaperSection><aside className="receipt"><div className="receipt-mark">GSTH</div><Eyebrow>Included totals</Eyebrow><p className="id-cell">AUG 2026 · CLIENT A</p><div className="receipt-lines">{receiptTotals.map((line) => <div className={line.label === "Total" ? "receipt-total" : ""} key={line.label}><span>{line.label}</span><Money value={line.value}/></div>)}</div><p className="mt-6 text-center font-note text-lg">Reviewed totals only</p></aside></div><SalesDrawer row={selected} close={() => setSelected(null)} save={(state) => { if (selected) setStates((old) => ({...old, [selected.id]: state})); setSelected(null); }}/></div>;
}
function SalesDrawer({ row, close, save }: { row: (typeof salesRows)[number] | null; close: () => void; save: (state: string) => void }) { const [state, setState] = useState("Reviewed"); const [note, setNote] = useState(""); return <Sheet open={Boolean(row)} onOpenChange={(open) => !open && close()}><SheetContent className="evidence-sheet"><SheetHeader><Eyebrow>{row?.id}</Eyebrow><SheetTitle className="font-display text-3xl">Review sales row</SheetTitle><SheetDescription>Set a human review state and leave a traceable note.</SheetDescription></SheetHeader>{row && <div className="mt-8 space-y-5"><div className="ledger-page"><p>{row.customer}</p><Money className="mt-4 text-3xl" value={row.taxable + row.tax}/></div><div className="segmented">{["Reviewed","Excluded","Unresolved"].map((option) => <Button variant={state === option ? "default" : "outline"} key={option} onClick={() => setState(option)}>{option}</Button>)}</div><Textarea placeholder="Review note…" value={note} onChange={(e) => setNote(e.target.value)}/><Button className="w-full" disabled={!note.trim()} onClick={() => save(state)}>Save row review</Button></div>}</SheetContent></Sheet>; }

export function WorksheetScreen() {
  const [step, setStep] = useState(1); const [decisions, setDecisions] = useState<ItcDecision[]>(initialItcDecisions); const [decisionNote, setDecisionNote] = useState(""); const [adjustments, setAdjustments] = useState([{ id: "ADJ-001", type: "Other liability", head: "CGST", amount: 5, note: "Late fee correction", voided: false }]); const [drafts, setDrafts] = useState(priorDrafts); const [approvalNote, setApprovalNote] = useState(""); const [approval, setApproval] = useState<"Draft"|"APPROVED"|"REOPENED"|"FILED (USER-REPORTED)">("Draft"); const [reference, setReference] = useState(""); const [reopenReason, setReopenReason] = useState(""); const blockers = decisions.filter((item) => item.decision === "undecided").length;
  const setDecision = (id: string, decision: ItcDecision["decision"]) => setDecisions((rows) => rows.map((row) => row.id === id ? {...row, decision} : row));
  const bulkMatched = () => setDecisions((rows) => rows.map((row) => row.finding === "matched" && row.decision === "undecided" ? {...row, decision: "claim"} : row));
  const bulkNotClaimed = () => setDecisions((rows) => rows.map((row) => row.decision === "undecided" ? {...row, decision: "not_claimed"} : row));
  const addAdjustment = () => setAdjustments((rows) => [...rows, { id: `ADJ-${String(rows.length + 1).padStart(3,"0")}`, type: adjustmentTypes[0] ?? "Other liability", head: taxHeads[0] ?? "IGST", amount: 0, note: "New manual adjustment", voided: false }]);
  const saveDraft = () => setDrafts((rows) => [{id:`DRF-202608-00${rows.length + 1}`, time:"29 AUG 2026 · 20:56", state:"Draft", by:"Priya Shah"}, ...rows]);
  return <div className="open-ledger animate-fade-in"><aside className="ledger-steps">{["Choose inputs","ITC decisions","Adjustments","Live worksheet","Drafts & approval"].map((label,index) => <button className={cn(step === index + 1 && "active", step > index + 1 && "complete")} key={label} onClick={() => setStep(index + 1)}><span>{step > index + 1 ? <Check/> : index + 1}</span><b>{label}</b></button>)}</aside><div className="ledger-content">
    {step === 1 && <LedgerStep eyebrow="Step one" title="Choose inputs"><div className="grid gap-4 md:grid-cols-2"><VersionChoice title="Sales version" version="SAL-V2 · Committed"/><VersionChoice title="Reconciliation run" version="RUN-2508-03 · Current"/></div><p className="margin-note">Both inputs were committed and reviewed on 29 August.</p><StepNext onClick={() => setStep(2)}/></LedgerStep>}
    {step === 2 && <LedgerStep eyebrow="Step two" title="ITC decisions"><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={bulkMatched}>Claim undecided matched (7)</Button><Button variant="outline" onClick={bulkNotClaimed}>Mark all undecided as not claimed</Button></div><Textarea className="mt-3" value={decisionNote} onChange={(e) => setDecisionNote(e.target.value)} placeholder="Required note for bulk or row decisions…"/><div className="mt-4 table-wrap"><table><thead><tr><th>Finding</th><th>Purchase</th><th>Eligible ITC</th><th>Decision</th></tr></thead><tbody>{decisions.map((row) => <tr key={row.id}><td>{row.finding.replaceAll("_"," ")}</td><td className="id-cell">{row.record}</td><td><Money value={row.amount}/></td><td><select className="native-select" value={row.decision} onChange={(e) => setDecision(row.id, e.target.value as ItcDecision["decision"])}><option value="undecided">Set…</option><option value="claim" disabled={row.finding !== "matched"}>claim</option><option value="not_claimed">not claimed</option><option value="deferred">deferred</option></select>{row.finding !== "matched" && <small className="ml-2 text-muted-foreground">Claim unavailable</small>}</td></tr>)}</tbody></table></div><StepNext onClick={() => setStep(3)}/></LedgerStep>}
    {step === 3 && <LedgerStep eyebrow="Step three" title="Adjustments"><div className="space-y-3">{adjustments.map((adj) => <div className={cn("adjustment-row", adj.voided && "voided")} key={adj.id}><span className="id-cell">{adj.id}</span><select className="native-select" value={adj.type} onChange={(e) => setAdjustments((rows) => rows.map((r) => r.id === adj.id ? {...r,type:e.target.value}:r))}>{adjustmentTypes.map((type) => <option key={type}>{type}</option>)}</select><select className="native-select" value={adj.head}>{taxHeads.map((head) => <option key={head}>{head}</option>)}</select><Input type="number" value={adj.amount} onChange={(e) => setAdjustments((rows) => rows.map((r) => r.id === adj.id ? {...r,amount:Number(e.target.value)}:r))}/><Input value={adj.note}/><Button size="icon" variant="ghost" title="Void adjustment" onClick={() => setAdjustments((rows) => rows.map((r) => r.id === adj.id ? {...r,voided:true}:r))}><X/></Button>{adj.voided && <span className="stamp stamp-small">VOID</span>}</div>)}</div><Button className="mt-4" variant="outline" onClick={addAdjustment}><Plus/> Add adjustment</Button><p className="margin-note">Voided entries stay visible so the worksheet’s history remains intact.</p><StepNext onClick={() => setStep(4)}/></LedgerStep>}
    {step === 4 && <LedgerStep eyebrow="Step four" title="Live worksheet"><div className={cn("blocker-note", blockers ? "has-blockers" : "clear")}><AlertTriangle/>{blockers ? `${blockers} ITC decisions remain unresolved` : "No blockers"}</div><div className="mt-5 table-wrap worksheet-table"><table><thead><tr><th>Head</th><th>Output tax</th><th>Liability adj.</th><th>Liability</th><th>ITC claimed</th><th>ITC reversal</th><th>Other credit</th><th>Credit</th><th>Net</th></tr></thead><tbody>{worksheetRows.map((row) => <tr key={row.head}><td className="id-cell">{row.head}</td><td><Money value={row.output}/></td><td><Money value={row.liabilityAdj}/></td><td><Money value={row.liability}/></td><td><Money value={row.itc}/></td><td><Money value={row.reversal}/></td><td><Money value={row.creditAdj}/></td><td><Money value={row.credit}/></td><td><Money className={row.net < 0 ? "text-status-done" : ""} value={row.net}/></td></tr>)}</tbody><tfoot><tr><td>Total</td>{[315,5,320,180,0,0,180,140].map((value,index) => <td key={index}><Money value={value}/></td>)}</tr></tfoot></table></div><div className="mt-5 flex justify-end"><Button onClick={saveDraft}><Save/> Save draft snapshot</Button></div><StepNext onClick={() => setStep(5)}/></LedgerStep>}
    {step === 5 && <LedgerStep eyebrow="Step five" title="Drafts & approval"><div className="draft-sheet"><div><Eyebrow>Latest draft</Eyebrow><h3 className="font-display text-3xl">DRF-202608-004</h3><p className="id-cell mt-1">29 AUG 2026 · 20:56</p></div>{approval !== "Draft" && <div className={cn("stamp stamp-large", approval.includes("FILED") && "stamp-green")}>{approval}</div>}<div className="mt-16 grid gap-3 md:grid-cols-2"><Textarea value={approvalNote} onChange={(e) => setApprovalNote(e.target.value)} placeholder="Approval note required…"/><Button disabled={blockers > 0 || !approvalNote.trim()} title={blockers > 0 ? `${blockers} unresolved ITC decisions block approval` : !approvalNote.trim() ? "Add an approval note first" : undefined} onClick={() => setApproval("APPROVED")}><Stamp/> Approve</Button><Button variant="outline" onClick={() => downloadDemo()}><Download/> Export draft workbook</Button><div className="filing-box"><Input value={reference} onChange={(e) => setReference(e.target.value)} placeholder="User-reported filing reference"/><Button variant="outline" disabled={!reference.trim() || approval !== "APPROVED"} onClick={() => setApproval("FILED (USER-REPORTED)")}>Mark filed</Button><small>user-reported, not verified</small></div></div>{approval === "APPROVED" && <p className="margin-note">Approved by Priya Shah · 29 AUG 2026 · 20:56</p>}{approval !== "Draft" && <div className="mt-5 border-t border-ledger-line pt-5"><Input value={reopenReason} onChange={(e) => setReopenReason(e.target.value)} placeholder="Required reason to reopen…"/><Button className="mt-2" variant="destructive" disabled={!reopenReason.trim()} onClick={() => setApproval("REOPENED")}><RotateCcw/> Reopen approval</Button></div>}</div><div className="mt-6"><Eyebrow>Earlier drafts · fan open</Eyebrow><div className="draft-pile">{drafts.map((draft,index) => <button style={{ transform: `rotate(${(index-1)*1.2}deg)` }} key={draft.id}><span className="id-cell">{draft.id}</span><b>{draft.state}</b><small>{draft.time} · {draft.by}</small></button>)}</div></div><p className="mt-8 text-xs text-muted-foreground">No set-off, rounding or cash payable is computed.</p></LedgerStep>}
  </div></div>;
}

function LedgerStep({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section><Eyebrow className="text-primary">{eyebrow}</Eyebrow><h2 className="mb-6 mt-1 font-display text-4xl">{title}</h2>{children}</section>; }
function StepNext({ onClick }: { onClick: () => void }) { return <div className="mt-7 flex justify-end"><Button onClick={onClick}>Continue <ArrowRight/></Button></div>; }
function downloadDemo() { const blob = new Blob(["GST Helper synthetic demo workbook\nNot for filing"], {type:"text/plain"}); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "gst-helper-draft-demo.txt"; a.click(); URL.revokeObjectURL(url); }

export function CategoriesScreen() {
  const [rows, setRows] = useState(categoryRows); const [mapRows, setMapRows] = useState(mappings);
  const decide = (id: string, state: string) => setRows((items) => items.map((item) => item.id === id ? {...item,state}:item));
  return <div className="space-y-6 animate-fade-in"><PaperSection><div className="section-heading"><div><Eyebrow>Purchase classification</Eyebrow><h2 className="font-display text-2xl">Suggested categories</h2></div><StatusChip tone="needs">3 decisions open</StatusChip></div><div className="table-wrap"><table><thead><tr><th>Record</th><th>Supplier & narration</th><th>Suggestion</th><th>Source</th><th>Decision</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td className="id-cell">{row.id}</td><td><b>{row.supplier}</b><small className="block text-muted-foreground">{row.narration}</small></td><td><span className="category-chip">{row.suggested}</span></td><td>{row.source}</td><td><div className="flex gap-1"><Button size="sm" variant={row.state === "Accepted" ? "default" : "outline"} onClick={() => decide(row.id,"Accepted")}><Check/> Accept</Button><Button size="sm" variant="outline" onClick={() => decide(row.id,"Rejected")}><X/> Reject</Button><select className="native-select" aria-label={`Choose category for ${row.id}`} onChange={() => decide(row.id,"Manual")}><option>Choose…</option><option>Capital goods</option><option>Professional fees</option><option>Freight</option></select></div></td></tr>)}</tbody></table></div></PaperSection><PaperSection><div className="section-heading"><div><Eyebrow>Client rules</Eyebrow><h2 className="font-display text-2xl">Approved mappings</h2></div><Button variant="outline"><Plus/> Add mapping</Button></div><div className="ledger-list">{mapRows.map((mapping) => <div className="ledger-entry" key={mapping.supplier}><span><b>{mapping.supplier}</b><small className="block text-muted-foreground">Effective {mapping.effective}</small></span><span className="category-chip">{mapping.category}</span><StatusChip tone={mapping.status === "Active" ? "done" : "waiting"}>{mapping.status}</StatusChip><Button size="sm" variant="ghost" disabled={mapping.status !== "Active"} onClick={() => setMapRows((items) => items.map((item) => item.supplier === mapping.supplier ? {...item,status:"Inactive"}:item))}>Deactivate</Button></div>)}</div></PaperSection></div>;
}

export function HistoryScreen() {
  const [query,setQuery] = useState(""); const [client,setClient] = useState("All clients");
  const events = useMemo(() => auditEvents.filter((event) => (client === "All clients" || event.client.startsWith(client)) && `${event.action} ${event.detail} ${event.actor}`.toLowerCase().includes(query.toLowerCase())),[query,client]);
  return <div className="space-y-5 animate-fade-in"><div className="flex flex-wrap gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search actions, details or actors…" value={query} onChange={(e) => setQuery(e.target.value)}/></div><FilterSelect value={client} setValue={setClient} label="Client" options={["All clients",...clients.map((item) => item.name)]}/></div><div className="receipt-roll">{events.map((event,index) => <article className={cn("audit-line", index > 0 && event.day !== events[index - 1]?.day && "new-day")} key={`${event.time}-${event.action}`}><div className="audit-time"><Eyebrow>{event.day}</Eyebrow><span>{event.time}</span></div><div><Eyebrow className="text-primary">{event.action}</Eyebrow><h3>{event.client}</h3><p>{event.detail}</p></div><span className="audit-actor">{event.actor}</span></article>)}{!events.length && <EmptyState title="No receipt lines" detail="Try a broader search or another client."/>}</div></div>;
}